name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ps2exe
        shell: pwsh
        run: Install-Module ps2exe -Scope CurrentUser -Force

      - name: Build executable
        shell: pwsh
        run: ./build/build.ps1

      - name: Check EXE
        shell: pwsh
        run: |
          Get-ChildItem -Path dist -Filter *.exe
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Steam-Commander
          path: dist/*.exe

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: dist/*.exe
          generate_release_notes: true
